---
title: "Shiny static figures"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r}

library(tidyverse)
library(magrittr)

dat <- read.csv("./data/shiny_data.csv")

dat %<>% filter(Group!="primates")  # just for now bc disease is missing

dat %<>% distinct(HostCorrectedName, .keep_all = TRUE)

```


```{r, eval=FALSE}
# summary of threat variable
table(dat$Threat)
table(dat$ThreatDic)
table(dat$ThreatDic2)

# summary of group
table(dat$Group)

# summary of group x threat
dat %>%
  group_by(Group, ThreatDic2, ThreatDis) %>%
  summarise (n = n()) %>%
  mutate(freq = n / sum(n))

```

```{r}

dat %>%
  filter(ThreatDic==0, ThreatDis==0) %>%
  mutate(type="NonThreatened") -> dfNon
  
dat %>%
  filter(ThreatDic==1, ThreatDis==0) %>%
  mutate(type="ThreatOther") -> dfT

dat %>%
  filter(ThreatDic==1, ThreatDis==1) %>%
  mutate(type="ThreatDisease") -> dfTD

dat %>%
  filter(ThreatDic==1, ThreatDis==1) %>%
  mutate(type="Disease") -> dfD

dat2 <- bind_rows(dfNon, dfT, dfTD, dfD)

dat2 %>% group_by(Group, type) %>%
  tally()

dat %>% 
  group_by(Group) %>% 
  tally()


#write.csv(dat2, "distinct-hosts.csv")

```


```{r}
# threat variable on top 
# and colors should be more intuitive

dat2 %>% 
  group_by(Group, type) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=Group)) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")

# filter by group type - host family
# make some sort of automated title
dat2 %>% 
  filter(Group=="carnivores") %>%
  group_by(HostFamily, type) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=HostFamily)) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

dat2 %>% 
  filter(Group=="ungulates") %>%
  group_by(HostFamily, type) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=HostFamily)) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# filter by continent
dat2 %>% 
  filter(continent=="North America") %>%
  group_by(HostFamily, type) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=HostFamily)) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

dat2 %>% 
  filter(continent=="Africa") %>%
  group_by(HostFamily, type) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=HostFamily)) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# filter by mass
# 0-20 20-60 60+ 
dat2 %>% 
  filter(!is.na(massKG)) %>%
  mutate(mass2=ifelse(massKG<75, 0, 1)) %>%
  group_by(mass2, type, Group) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=factor(mass2))) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  facet_grid(Group ~ .) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# filter by home range
# 0-
dat2 %>% 
  filter(!is.na(hostHomeRange)) %>%
  mutate(range2 = ifelse(log(hostHomeRange) < 2, 0, 1)) %>%
  group_by(range2, type, Group) %>% 
  tally() %>%
  ggplot(aes(fill=type, y=n, x=factor(range2))) + 
  geom_bar(stat="identity", position = "fill") + 
  labs(y="", fill="")  + 
  facet_grid(Group ~ .) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

